apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    #helm costums
    app.kubernetes.io/managed-by: "Helm"
    meta.helm.sh/release-namespace: "default"
    meta.helm.sh/release-name: {{ .Release.Name }}

    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: postgresql
  name: data-{{ .Release.Name }}-postgresql-0
  namespace: default
spec:
  storageClassName: {{ index .Values "eqms" "storage" "class" | default "default" }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeMode: Filesystem

---

#for static hive metastore service adress
apiVersion: v1
kind: Service
metadata:
  name: eqms-hive-metastore
  namespace: default
spec:
  ports:
  - name: thrift
    port: 9083
    protocol: TCP
    targetPort: 9083
  selector:
    app.kubernetes.io/component: metastore
    app.kubernetes.io/name: hive-metastore
  type: ClusterIP

# ---

# #for static postgres service adress
# apiVersion: v1
# kind: Service
# metadata:
#   name: eqms-postgresql
#   namespace: default
# spec:
#   ports:
#   - name: tcp-postgresql
#     port: 5432
#     protocol: TCP
#     targetPort: tcp-postgresql
#   selector:
#     app.kubernetes.io/name: postgresql
#   type: ClusterIP