# commands to install eqms using argocd

apiVersion: v1
kind: Secret
metadata:
  name: eqms-test-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: "https://github.com/DavidGitter/data-analytics-earthquake-monitoring-system.git" 
  type: git

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eqms
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/DavidGitter/data-analytics-earthquake-monitoring-system.git"
    path: src/eqms
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
      parameters:
      - name: "eqms.storage.class"
        value: "standard"            # insert your storage-class-name here
      - name: "minio-operator.tenants[0].pools[0].storageClassName"
        value: "standard"            # insert your storage-class-name here
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: false